usersignup/urls.py
from django.urls import path
from . import views

app_name = 'usersignup'
urlpatterns = [
    path('', views.index, name='homepage'),
    path('login/', views.login, name='login_page'),
    path('signup/', views.create_profile, name='create_profile'),
    path('signup/final', views.create_web_profile, name='web_profile_create'),
    path('welcome/', views.redirect_page, name='welcome_page')
]

usersignup/models.py
from django.db import models


class WebDetail(models.Model):
    # user = models.OneToOneField(UserDetail, on_delete=models.CASCADE, primary_key=True,)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)

    def __str__(self):
        return self.username


class UserDetail(models.Model):
    first_name = models.CharField(max_length=225)
    middle_name = models.CharField(max_length=255, blank=True, null=True)
    last_name = models.CharField(max_length=255)
    email = models.EmailField()
    user = models.OneToOneField(WebDetail, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return self.first_name

usersignup/forms.py
import re
from .models import UserDetail
from django import forms
from django.core.validators import ValidationError


def has_only_english(word):
    all_alphabets = '[\u0041-\u007A\-]*'
    return bool(re.fullmatch(all_alphabets, word))


def has_symbols(word):
    symbols = '[\u005B-\u0060\-]*'
    return bool(re.fullmatch(symbols, word))


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=95,
        min_length=6,
        label="",
        widget=forms.TextInput(
            attrs={'placeholder': 'Username'}
        )
    )
    password = forms.CharField(
        max_length=128,
        min_length=8,
        label="",
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Password'}
        ),
    )


class CreateProfileForm(forms.Form):
    first_name = forms.CharField(
        max_length=26,
        min_length=2,
        label="",
        widget=forms.TextInput(
            attrs={'placeholder': 'First name'}
        )
    )
    middle_name = forms.CharField(
        max_length=26,
        min_length=2,
        label="",
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Middle name'}
        )
    )
    last_name = forms.CharField(
        max_length=26,
        min_length=2,
        label="",
        widget=forms.TextInput(
            attrs={'placeholder': 'Last name'}
        )
    )
    email = forms.EmailField(
        max_length=254,
        min_length=10,
        label="",
        widget=forms.TextInput(
            attrs={'placeholder': 'Email'}
        ),
    )

    def clean_first_name(self):
        if has_only_english(self.cleaned_data['first_name']):
            return self.cleaned_data['first_name']
        error_message = 'This has to be plain english, e.g John'
        raise ValidationError(error_message, code='invalid_language')

    def clean_first_name_to_check_for_symbols(self):
        if has_only_english(self.cleaned_data['first_name']):
            return self.cleaned_data['first_name']
        error_message = 'Name cannot contain \' [, \, ], ^, -, ` \''
        raise ValidationError(error_message, code='symbol_included')

    def clean_middle_name(self):
        if has_only_english(self.cleaned_data['middle_name']):
            return self.cleaned_data['middle_name']
        error_message = 'This has to be plain english, e.g Maxwell'
        raise ValidationError(error_message, code='invalid_language2')

    def clean_last_name(self):
        if has_only_english(self.cleaned_data['last_name']):
            return self.cleaned_data['last_name']
        error_message = 'This has to be plain english, e.g Smith'
        raise ValidationError(error_message, code='invalid_language3')

    # def clean_email(self, *args, **kwargs):
    #     email = self.cleaned_data.get('email')
    #     if not email.endswith('.com'):
    #         raise forms.ValidationError(
    #             _('This is not a valid email'),
    #             code='Invalid'
    #         )
    #     return email


# TODO:
#  i need to adjust the redirect function so that a user would not just
#  in the url and then have access to the last user signup detail.
#   i also need to add a gender to the forms view

# TODO: I need to clean every data that comes in, and also google search the minimum and maximum length for
#  every field listed above.

'''
Unicode character for punctuations and symbols 0020-002F
Unicode character for digits 0030-0039
Unicode character for punctuations and symbols 003A-0040
Unicode character for english uppercase 0041-005A
Unicode character for punctuations and symbols 005B-0060
Unicode character for english lowercase 0061-007A
Unicode character for punctuations and symbols 007B-007E
'''

usersignup/views.py
from django.shortcuts import render, reverse
from .models import UserDetail, WebDetail
from .forms import CreateProfileForm, LoginForm
from django.shortcuts import redirect
from django.http import HttpResponse
from django.views import View

# TODO: i need to convert these views to class based views so i need to do some research about class based
#   views and i need to implement them here


def index(requests):
    context = {}
    return render(requests, 'signup/index.html', context)


def login(requests):
    form = LoginForm()
    if requests.method == 'POST':
        form = LoginForm(requests.POST)
        if form.is_valid():
            try:
                WebDetail.objects.get(**form.cleaned_data)
                return HttpResponse('<h1>You are logged on</h1>')
            except WebDetail.DoesNotExist:
                context = {
                    'login_error': 'Sorry, you do not have an account, try creating one!',
                }
                return render(requests, 'signup/profile.html', context)
    context = dict(form=form)
    return render(requests, 'signup/login.html', context)


def create_profile(requests):
    form = CreateProfileForm()
    if requests.method == "POST":
        form = CreateProfileForm(requests.POST)
        if form.is_valid():
            UserDetail.objects.create(**form.cleaned_data)
            # This is the email verification code
            # inactive_user = send_verification_email(requests, form)
            # inactive_user.cleaned_data['email']
            user_data = form.cleaned_data
            global user
            user = user_data
            return redirect('signup:web_profile_create')
    context = dict(form=form)
    return render(requests, 'signup/profile.html', context)


# TODO: i need to confirm the email verification. because i tried it and it didn't go well so i need
#  to connect to the internet and check it

def create_web_profile(requests):
    form = LoginForm()
    if requests.method == "POST":
        form = LoginForm(requests.POST)
        if form.is_valid():
            WebDetail.objects.create(**form.cleaned_data)
            return redirect('signup:welcome_page')
    context = dict(form=form)
    return render(requests, 'signup/web_profile.html', context)


def redirect_page(requests):
    # first_name, last_name = user['first_name'], user['last_name']
    context = {
        # 'first_name': first_name,
        # 'last_name': last_name,
    }
    return render(requests, 'signup/redirect_page.html', context)


# TODO: I need to modify the app so that a user cannot access the previous signup data from the url
#   i also need each signup to carry a unique identification so it is easily identified and that would be
#   stored in the database for the user.

# TODO: I need to add some style and color to this app, so i can publish it on github.

usersignup/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Site name</title>
    {% block stylesheet %}
        
    {% endblock %}
</head>
<body>
    {% block content %}
        replace me
    {% endblock %}
</body>
</html>

usersignup/templates/signup/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<title>Site name</title>
</head>
<body>
	<h1 class="header">Name of site</h1>
	<p><b class="info">Site informative note. &#128513 </b><br>{% lorem %}</p>
	<div id="urls">
		<b><a href="{% url 'usersignup:login_page' %}">Login</a></b>
		<br>OR<br>
		<b><a href="{% url 'usersignup:create_profile' %}">Create new account</a></b>
	</div>
	<!-- I need to modify the css and add some coloring, images and the rest,
	because its looking preety dull. i wrote this 3-4-21 @ 16:58 -->
</body>
</html>

usersignup/templates/signup/login.html
{% extends 'base.html' %}

{% block stylesheet %}
    {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'login.css' %}">
{% endblock %}

{% block content %}
<div id="form">
    <form method="POST">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="login">Login</button>
</form>
</div>

{% endblock %}

usersignup/templates/signup/profile.html
{% extends 'base.html' %}

{% block content %}
{% if login_error %}
    <strong><big>{{ login_error }}</big></strong><br>
    <a href="{% url 'usersignup:create_profile' %}">Create an account</a>
{% else %}
    <form method="POST">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Next</button>
</form>
{% endif %}
{% endblock %}

usersignup/templates/signup/redirect_page.html
{% extends 'base.html' %}

{% block content %}
<!--    <h2>Hello <big>{{ first_name }}</big> thanks for signing up.</h2>-->
<p>We will redirect you shortly to our home page.</p>

<!-- This below is the timed JavaScript redirect function -->
<div id="counter">5</div>
<script>
    setInterval(function() {
        var div = document.querySelector("#counter");
        var count = div.textContent * 1 - 1;
        div.textContent = count;
        if (count <= 0) {
            window.location.replace("{% url 'homepage:homepage' %}");
        }
    }, 1000);
</script>
<!-- I need to change the url in the link, so that each signup has a unique identifier
so it can't be accessed through the url.
-->
{% endblock %}

usersignup/templates/signup/web_profile.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}